### ISSUE TITLE
Demo for water like GIF in ReadMe

### ISSUE THREAD

**Issue by Uricorn** [synlogic/Syns-Unity-Shaders#1]
Hi,

I tried using this but I have not been able to get the water in my scene to look like the one from your GIF.

Can you create a demo scene/prefab for it, or at least share a screenshot of your settings?

Thanks!

**Comment by synlogic** [comment]
Hey!  Sorry for taking way to long to get back on this.  Here in the next few days (possibly today) I will be releasing an overhaul of all of the shaders, and cleaning things up a lot.  I will be including example scenes for both the water and avatar shaders.
